name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  steps:
  - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://orgaa6f4825.crm.dynamics.com'
        user-name: ${{ secrets.USER }}
        password-secret: ${{ secrets.PASSWORD }}
        
#  Release-solution-ALMLab:
#    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
#    with:
#      #You can specify the solution name here
#      solution_name: ALMLab
#      #Update your values here
#      BUILD_ENVIRONMENT_URL: https://orgf5b5f229.crm.dynamics.com
#      PRODUCTION_ENVIRONMENT_URL: https://org9f7ab155.crm.dynamics.com
   
